/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Administrativo;
import Modelo.Alumno;
import Modelo.Auxiliar;
import Modelo.Empleado;
import Modelo.Partido;
import Modelo.Persona;
import Modelo.Profesor;
import Modelo.Responsable;
import Negocio.Escuela;
import Negocio.Matricula;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class Principal extends javax.swing.JFrame {
private Escuela e=new Escuela();
private Empleado ep=new Empleado();
private Persona p=new Persona();
private Alumno a=new Alumno();
private Date f=new Date();
private Profesor pro=new Profesor();
private Auxiliar as=new Auxiliar();
private Responsable re=new Responsable();
private SimpleDateFormat s=new SimpleDateFormat("DD/MM/YYYY");
private Administrativo ad=new Administrativo();
private Matricula matricula=new Matricula();
private final int insumosDeportivos=5000000;
private ArrayList<Partido> res=new ArrayList();

private Double gastosSueldos,matriculasPensiones;
    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        
        this.setResizable(false);
        jPanel1.setVisible(false);
        panelResponsable.setVisible(false);
        textSueldo.setEnabled(false);
        textEspecialidad.setEnabled(false);
        textEntrada.setEnabled(false);
        textSalida.setEnabled(false);
        txtMa.setEnabled(false);
        txtPension.setEnabled(false);
       
        btnMatricular.setEnabled(false);
        btnNuevoHijo.setEnabled(false);
        btnFinalizar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        textEspecialidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textSueldo = new javax.swing.JTextField();
        textEntrada = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textSalida = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPension = new javax.swing.JTextField();
        txtFecha = new javax.swing.JLabel();
        textFecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        panelResponsable = new javax.swing.JPanel();
        btnNuevoHijo = new javax.swing.JButton();
        btnMatricular = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtTR = new javax.swing.JTextField();
        txtCR = new javax.swing.JTextField();
        txtNR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtER = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboGeneroR = new javax.swing.JComboBox<>();
        btnFinalizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtRetirar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escuela de basketball");

        jLabel2.setText("Nombre");

        jLabel3.setText("Direccion");

        jLabel4.setText("Cedula");

        jLabel5.setText("Telefono");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Profesor", "Auxiliar", "Administrador", "Alumno" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jLabel6.setText("TIpo");

        jLabel7.setText("Genero");

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino" }));
        comboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGeneroActionPerformed(evt);
            }
        });

        jLabel8.setText("Especialidad");

        jLabel9.setText("Sueldo");

        jLabel10.setText("Final Salida");

        jLabel11.setText("Fecha entrada");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel12.setText("Matricula");

        jLabel13.setText("Pension");

        txtFecha.setText("Fecha");

        jLabel14.setText("DD/MM/YYYY");

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNuevoHijo.setText("Nuevo hijo");
        btnNuevoHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoHijoActionPerformed(evt);
            }
        });

        btnMatricular.setText("Matricular Alumno");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });

        jLabel20.setText("Cedula");

        txtTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTRActionPerformed(evt);
            }
        });

        jLabel16.setText("Nombre");

        jLabel18.setText("Telefono");

        jLabel19.setText("Email");

        jLabel21.setText("Registro de responsable");

        jLabel15.setText("Genero");

        comboGeneroR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "masculino", "femenino" }));

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResponsableLayout = new javax.swing.GroupLayout(panelResponsable);
        panelResponsable.setLayout(panelResponsableLayout);
        panelResponsableLayout.setHorizontalGroup(
            panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResponsableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResponsableLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResponsableLayout.createSequentialGroup()
                        .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelResponsableLayout.createSequentialGroup()
                                    .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19))
                                    .addGap(25, 25, 25))
                                .addGroup(panelResponsableLayout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(panelResponsableLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(87, 87, 87)))
                        .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNR)
                            .addComponent(txtER)
                            .addComponent(txtCR)
                            .addComponent(txtTR, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMatricular, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(btnNuevoHijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21)
                            .addComponent(comboGeneroR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        panelResponsableLayout.setVerticalGroup(
            panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResponsableLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelResponsableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(comboGeneroR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMatricular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoHijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Calcular dinero anual");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton2.setText("Retirar Alumno");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reportar Accidente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel22.setText("Cedula Alumno");

        jButton6.setText("Registrar Campeonato");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Registrar Partido");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRetirar)
                    .addComponent(jTextField1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(txtFecha))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textDireccion)
                                    .addComponent(textCedula)
                                    .addComponent(textTelefono)
                                    .addComponent(comboGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textEspecialidad)
                                    .addComponent(textSueldo)
                                    .addComponent(textEntrada)
                                    .addComponent(textSalida)
                                    .addComponent(txtMa)
                                    .addComponent(txtPension)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnRegistrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textFecha)
                                    .addComponent(textNombre))))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha)
                                    .addComponent(jLabel14)))
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(textSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(textSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(jButton1))
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void mostrar(){
 this.setVisible(true);

}
    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        if(comboTipo.getSelectedItem().equals("Administrador")||comboTipo.getSelectedItem().equals("Auxiliar")||comboTipo.getSelectedItem().equals("Profesor")){
        textSueldo.setEnabled(true);
        }else{textSueldo.setEnabled(false);}
        
        if(comboTipo.getSelectedItem().equals("Alumno")){
            JOptionPane.showMessageDialog(null, "Para Matricular a un alumno deberá registrar a su correspondiente acudiente o responsable");
        panelResponsable.setVisible(true);
        txtMa.setEnabled(true);
        txtPension.setEnabled(true);
        btnRegistrar.setEnabled(false);
        btnFinalizar.setEnabled(true);
        btnMatricular.setEnabled(true);
        btnNuevoHijo.setEnabled(true);
        }else{
            btnRegistrar.setEnabled(true);
            panelResponsable.setVisible(false);
            btnFinalizar.setEnabled(true);
       
        btnMatricular.setEnabled(false);
        btnNuevoHijo.setEnabled(false);
        txtMa.setEnabled(false);
        txtPension.setEnabled(false);
        
        }
        if(comboTipo.getSelectedItem().equals("Administrador")){
        textEntrada.setEnabled(true);
        textSalida.setEnabled(true);
        }else{
        textEntrada.setEnabled(false);
        textSalida.setEnabled(false);
        
        
        }
        
        if(comboTipo.getSelectedItem().equals("Auxiliar")){
        
        
        }
        if(comboTipo.getSelectedItem().equals("Profesor")){
       
        textEspecialidad.setEnabled(true);
        }else{textEspecialidad.setEnabled(false);}
        
        if(comboTipo.getSelectedItem().equals("Seleccione")||comboTipo.getSelectedItem().equals("Alumno")||comboTipo.getSelectedItem().equals("Responsable")){
            
    
      
      
    }//GEN-LAST:event_comboTipoActionPerformed
    }
   public void agregarPartido(Partido p){
   res.add(p);
       System.out.println("Partido agregado");
   }
    public String saberGeneroR(){
    
    if(comboGeneroR.getSelectedItem().equals("Masculino")){
        return "Masculino";
    }else if(comboGeneroR.getSelectedItem().equals("Femenino")){
    
        return "Femenino";
    }else{
    
    return "NINGUN SELECCIONADO";
    }
    
    }
    public String saberGenero(){
    
    if(comboGenero.getSelectedItem().equals("Masculino")){
        return "Masculino";
    }else if(comboGenero.getSelectedItem().equals("Femenino")){
    
        return "Femenino";
    }else{
    
    return "NINGUN SELECCIONADO";
    }
    
    }
    private void comboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGeneroActionPerformed
        
         
        
        
        
    }//GEN-LAST:event_comboGeneroActionPerformed
public Integer calcularEdad(Date fecha){
    Date fechaA=new Date();
   return Math.abs(fechaA.getYear()-fecha.getYear());
    
    
    }
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
     
      jButton1.setEnabled(true);
        if(gastosSueldos==null||matriculasPensiones==null){
             
        gastosSueldos=0.0;
        matriculasPensiones=0.0;
        
        }
    
        
            
           
          
            
       if(comboTipo.getSelectedItem().equals("Profesor")){
           
        
            try {
                pro.setEspecialidad(textEspecialidad.getText());
                pro.setDireccion(textDireccion.getText());
                pro.setCedula(textCedula.getText());
                pro.setFechaNa(s.parse(textFecha.getText()));
                pro.setGenero(saberGenero());
                pro.setNombre(textNombre.getText());
                pro.setSueldo(Double.parseDouble(textSueldo.getText()));
                gastosSueldos+=(Double.parseDouble(textSueldo.getText()))*12;
                pro.setTelefono(textTelefono.getText());
            } catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        ep=pro;
        ep.setTipo("Profesor");
        e.registroEmpleado(ep);
       
           
    }  if(comboTipo.getSelectedItem().equals("Auxiliar")){
            try {
                int edad=calcularEdad(s.parse(textFecha.getText()));
                if((edad>=25 && edad<=35)&&(saberGenero().equals("Femenino"))){
                
                try {
               
                as.setDireccion(textDireccion.getText());
                as.setCedula(textCedula.getText());
                as.setFechaNa(s.parse(textFecha.getText()));
                as.setGenero(saberGenero());
                as.setNombre(textNombre.getText());
                as.setSueldo(Double.parseDouble(textSueldo.getText()));
                gastosSueldos+=(Double.parseDouble(textSueldo.getText()))*12;
                as.setTelefono(textTelefono.getText());
            } catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
                ep=as;
        ep.setTipo("Auxiliar");
        e.registroEmpleado(ep);
                }else{
                    if(saberGenero().equals("Masculino")){
                        JOptionPane.showMessageDialog(null,"Debe ser mujer");
                    }
                    JOptionPane.showMessageDialog(null,"No se encuentra en el rango de edad");
                
                }
            } catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
      
        
        
        
        
        }
    if(comboTipo.getSelectedItem().equals("Responsable")){
  
     try {
               
                re.setDireccion(textDireccion.getText());
                re.setCedula(textCedula.getText());
                re.setFechaNa(s.parse(textFecha.getText()));
                re.setGenero(saberGenero());
                re.setNombre(textNombre.getText());
                re.setTelefono(textTelefono.getText());
            } catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        p=re;
        p.setTipo("Responsable");
        e.registroPersona(p);
    }
    if(comboTipo.getSelectedItem().equals("Administrador")){
    
        
     try {
                
                ad.setDireccion(textDireccion.getText());
                ad.setCedula(textCedula.getText());
                ad.setFechaNa(s.parse(textFecha.getText()));
                ad.setGenero(saberGenero());
                ad.setNombre(textNombre.getText());
                ad.setSueldo(Double.parseDouble(textSueldo.getText()));
                gastosSueldos+=(Double.parseDouble(textSueldo.getText()))*12;
                ad.setTelefono(textTelefono.getText());
                ad.setFechaFin(s.parse(textSalida.getText()));
                ad.setFechaInicio(s.parse(textEntrada.getText()));
                
            } catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        ep=ad;
        ep.setTipo("Administrador");
        e.registroEmpleado(ep);
    
   
    }
    
    
        if(ep.getTipo()!=null){
        JOptionPane.showMessageDialog(null, ep.getTipo()+" registrado"+"");
        
        }else{
           JOptionPane.showMessageDialog(null, ep.getTipo()+" registrado"+"");
        }
        
        
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jPanel1.setVisible(true);
        
      areaTexto.setText(e.mostrarDatos()+"\n"+e.partidos(res));
        
        limpiar();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTRActionPerformed

    private void btnNuevoHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoHijoActionPerformed
        textNombre.setText("");
        textCedula.setText("");
        textTelefono.setText("");
        textFecha.setText("");
        textDireccion.setText("");
        System.out.println("");
    }//GEN-LAST:event_btnNuevoHijoActionPerformed
Double valorMatricula,valorPension;

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
   a=new Alumno();
        if(gastosSueldos==null||matriculasPensiones==null){
             
        gastosSueldos=0.0;
        matriculasPensiones=0.0;
        
        }
        
        
         if(comboTipo.getSelectedItem().equals("Alumno")){
             
             if(valorMatricula==null||valorPension==null){
             valorMatricula=0.0;
             valorPension=0.0;
             }
             
             valorMatricula+=Double.parseDouble(txtMa.getText());
             valorPension+=Double.parseDouble(txtPension.getText());
             
             
               matricula.setPension(valorPension);
               matricula.setValor(valorMatricula);
               
               
               
             if(re.getHijos()!=null){
                 
             if(re.getHijos().size()>=1){
                 JOptionPane.showMessageDialog(null,"Se le aplicara un descuento del 10% por tener "+(re.getHijos().size()+1)+" hijos");
                 
             }
             
             }
             
             
     try {
               
               
                a.setDireccion(textDireccion.getText());
                a.setCedula(textCedula.getText());
               a.setFechaNa(s.parse(textFecha.getText()));
                a.setGenero(saberGenero());
                a.setNombre(textNombre.getText());
               a.setTelefono(textTelefono.getText());
               
            } catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
                re.setDireccion(textDireccion.getText());
                re.setCedula(txtCR.getText());              
                re.setGenero(saberGeneroR());
                re.setNombre(txtNR.getText());
                re.setTelefono(txtTR.getText());
     
                re.agregarHijos(a);
                
                
                
                
        p=a;
        
        p.setTipo("Alumno");
        e.registroPersona(p);
        
        
        
        
        
        
        
        
        if(e.buscarResponsable(txtCR.getText())==true){
        
        }else{
        
        p=re;
        p.setTipo("Responsable");
        e.registroPersona(p);
        }
        
    }
        
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        
        Double nuevoValor=matricula.getValor();
      if(re.getHijos()!=null){
        if(re.getHijos().size()>1){
                  matricula.setValor(nuevoValor-(nuevoValor*0.10));
                                   matriculasPensiones+=matricula.getValor()+(matricula.getPension()*12);
            JOptionPane.showMessageDialog(null,"Valor matricula="+matricula.getValor());
            System.out.println("Valor pension="+matricula.getPension());
                 JOptionPane.showMessageDialog(null,"Descuento aplicado de "+nuevoValor*0.10);
             }else{
         matriculasPensiones+=matricula.getValor()+(matricula.getPension()*12);
         JOptionPane.showMessageDialog(null,"Valor matricula="+matricula.getValor());
        JOptionPane.showMessageDialog(null,"Valor pension="+matricula.getPension());
        
      }
      }
        
        re=new Responsable();
        a=new Alumno();
       
        for (int i = 0; i < re.getHijos().size(); i++) {
            
           // re.getHijos().get(i).get
        }
        
                 valorMatricula=0.0;
                 valorPension=0.0;
        limpiar();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      
    
    e.retirarEstudiante(txtRetirar.getText());
    
    
    
    
    
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      Double ingresoTotal=0.0;
      
      
      ingresoTotal=(matriculasPensiones-gastosSueldos)-5000000;
      
      if(ingresoTotal>0){
        areaTexto.setText("La universidad genero en matriculas y pensiones "+matriculasPensiones+" \ny gasto en sueldos "+gastosSueldos+"\nIngresos Totales "+ingresoTotal+"$");
        
      }else if(ingresoTotal<0){
      areaTexto.setText("La universidad genero en matriculas y pensiones "+matriculasPensiones+" \ny gasto en sueldos "+gastosSueldos+"\nLa universidad perdio "+ingresoTotal+"$");
      
      
      }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        Accidente a=new Accidente();
        a.mostrar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
RegistrarPartido pr=new RegistrarPartido();
       pr.mostrar();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        RegistrarCampeonato res=new RegistrarCampeonato();
        res.mostrar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        areaTexto.setText("");
        limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed
public void limpiar(){
textSueldo.setEnabled(false);
panelResponsable.setVisible(false);
        textEspecialidad.setEnabled(false);
        textEntrada.setEnabled(false);
        textSalida.setEnabled(false);
        txtMa.setEnabled(false);
        txtPension.setEnabled(false);
        
        btnMatricular.setEnabled(false);
        btnNuevoHijo.setEnabled(false);
        btnFinalizar.setEnabled(false);
textSueldo.setText("");
        textEspecialidad.setText("");
        textEntrada.setText("");
        textSalida.setText("");
        txtMa.setText("");
        txtPension.setText("");
        txtTR.setText("");
        txtNR.setText("");
        txtER.setText("");
        txtCR.setText("");
        textNombre.setText("");
        textTelefono.setText("");
        textDireccion.setText("");
        textCedula.setText("");
        textFecha.setText("");
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnNuevoHijo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JComboBox<String> comboGeneroR;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelResponsable;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textEntrada;
    private javax.swing.JTextField textEspecialidad;
    private javax.swing.JTextField textFecha;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textSalida;
    private javax.swing.JTextField textSueldo;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JTextField txtCR;
    private javax.swing.JTextField txtER;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNR;
    private javax.swing.JTextField txtPension;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtTR;
    // End of variables declaration//GEN-END:variables
}
